spring:
  datasource:
    url: jdbc:mysql://na-projectdb.cdebxlgvh3dh.us-east-1.rds.amazonaws.com:3306/csvmodel?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: password

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true



  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


